autoStart: false
autoApplyProfiles: true
hideTaskbar: true
shortcutProfiles:
- id: 9000
  keyCombination: ALT+F9
  windowComposition:
    positionX: 3433
    positionY: 0
    width: 1694
    height: 1447
    windowStyles:
    extendedWindowStyles:
- id: 9001
  keyCombination: ALT+F10
  windowComposition:
    positionX: 0
    positionY: 0
    width: 2560
    height: 1440
    windowStyles:
    - WS_VISIBLE
    extendedWindowStyles: 
- id: 9002
  keyCombination: ALT+F11
  windowComposition:
    positionX: 0
    positionY: 0
    width: 3440
    height: 1440
    windowStyles:
    - WS_VISIBLE
    extendedWindowStyles: 
windowProfiles:
- titleRegex: ^(192.168.178.78 - Remote Desktop Connection)$
  processName: mstsc
  windowComposition:
    positionX: 0
    positionY: -1
    width: 5120
    height: 1440
    windowStyles:
    - WS_VISIBLE
    extendedWindowStyles: 
- titleRegex: ^(Yakuza 4)$
  processName: Yakuza4
  windowComposition:
    positionX: 0
    positionY: 0
    width: 3440
    height: 1440
    delayMilliseconds: 20
    windowStyles:
    - WS_VISIBLE
    extendedWindowStyles:
- titleRegex: ^(Persona4 GOLDEN).*$
  processName: P4G
  windowComposition:
    positionX: 0
    positionY: 0
    width: 2560
    height: 1440
    windowStyles:
    - WS_VISIBLE
    extendedWindowStyles: